### ISSUE TITLE
Update for ESP-8266?

### ISSUE THREAD

**Issue by cjgaspari** [dr1rrb/diy-ikea-evedal#1]
Hey @dr1rrb -- just was curious if you ever got around to integrating the ESP-8266? I just recently picked up one of these as it was heavily price reduced >50% 

I came across this mod, which I'll probably implement, but was curious if you ever got the dimmer to work too? 

Thanks for putting together this guide, it's awesome!

**Comment by dr1rrb** [comment]
Hey @cjgaspari, unfortunately no, I never went there. The only one that I frequently dim is using an in-wall dimmer through a Zwave group.

**Comment by cjgaspari** [comment]
Thank you for the reply!!
